version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: snipeit-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - snipeit

  snipeit:
    image: snipe/snipe-it:latest
    container_name: snipeit-app
    restart: unless-stopped
    depends_on:
      - mysql
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - ./snipeit:/var/lib/snipeit
    networks:
      - snipeit

networks:
  snipeit:
    driver: bridge

volumes:
  mysql:
    driver: local
  snipeit:
    driver: local